apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mesh-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - cluster: k8s-lab
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: mesh-demo-{{cluster}}
    spec:
      project: default
      source:
        repoURL: https://github.com/rayabueg/cluster-applications.git
        targetRevision: main
        path: mesh-demo
      destination:
        server: '{{server}}'
        namespace: mesh-demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
